name: Deploy to DigitalOcean
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: srinivasjoshi/react-app-ecr:latest
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Trigger DO App Platform deployment
        run: |
          DEPLOYMENT_ID=$(doctl apps create-deployment ${{ secrets.DO_APP_ID }} --format ID --no-header)
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
          
      - name: Wait for deployment
        run: |
          echo "Waiting for deployment ${{ env.DEPLOYMENT_ID }}..."
          while true; do
            STATUS=$(doctl apps get-deployment ${{ secrets.DO_APP_ID }} ${{ env.DEPLOYMENT_ID }} --format Progress.Steps[0].Status --no-header)
            echo "Deployment status: $STATUS"
            if [ "$STATUS" = "SUCCESS" ]; then
              echo "✅ Deployment successful!"
              break
            elif [ "$STATUS" = "ERROR" ]; then
              echo "❌ Deployment failed!"
              exit 1
            fi
            sleep 10
          done